name: Canary testing

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/canary-testing.yml'
jobs:
  testing-canary:
    runs-on: test-runners
    steps:
      - name: Check out code
        id: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if exists
        run: |
          sh -c "ls -la ~/.aws/credentials; ls -la ~/.vault-token; pwd; id; whoami"